"""
Django settings for Lexis_Tools project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SERIALIZER salt key
SERIALIZER_SALT_KEY = os.getenv("SERIALIZER_SALT_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['lexistools.pythonanywhere.com', '127.0.0.1', 'localhost']


# SESSION SETTINGS
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365 * 2    # 2 year
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True      # Refresh expiry on each request
SESSION_COOKIE_SECURE = False           # Only over HTTPS
SESSION_COOKIE_HTTPONLY = True         # JS cannot access
SESSION_COOKIE_SAMESITE = 'Lax'        # Protect against CSRF


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'rest_framework',

    'Lexis_Tools_ai_models',
    'Lexis_Tools_apis',
    'Lexis_Tools_auth',
    'Lexis_Tools_blogs',
    'Lexis_Tools_pages',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'Lexis_Tools.middleware.AdminPanalSecurityMiddleware',
]

ROOT_URLCONF = "Lexis_Tools.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Lexis_Tools.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": os.getenv("DATABASE_NAME"),
#         "USER": os.getenv("DATABASE_USER"),
#         "PASSWORD": os.getenv("DATABASE_PASSWORD"),
#         "HOST": os.getenv("DATABASE_HOST"),
#         "PORT": os.getenv("DATABASE_PORT"),
#         "OPTIONS": {
#             "charset": "utf8mb4",
#             "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
#         }
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/static'
STATIC_URL = '/static/'


# Django Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
MAIL_SEND_TO = os.getenv("MAIL_SEND_TO")


# Avaiable AI Models Configurations

# LLM
LLM_PROVIDER_CHOICES = [
    ('GOOGLE', 'Google'),
    ('GROQ', 'Groq'),
    ('OPENAI', 'OpenAI'),
]

LLM_MODEL_CHOICES = {
    'GOOGLE': ['gemini-3-pro-preview', 'gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash'],
    'GROQ': ['openai/gpt-oss-120b', 'groq/compound', 'meta-llama/llama-4-maverick-17b-128e-instruct', 'moonshotai/kimi-k2-instruct-0905', 'meta-llama/llama-4-maverick-17b-128e-instruct', 'qwen/qwen3-32b'],
    'OPENAI': ["gpt-4.1", "gpt-4o", "gpt-4.1-mini", "gpt-4o-mini", "gpt-3.5-turbo"],
}


# TTS

TTS_PROVIDER_CHOICES = [
    ('GOOGLE', 'Google'),
    ('ELEVENLABS', 'ElevenLabs'),
]

TTS_MODEL_CHOICES = {
    'GOOGLE': ['gemini-2.5-flash-preview-tts', 'gemini-2.5-pro-preview-tts'],
    'ELEVENLABS': ['eleven_multilingual_v2', 'eleven_monolingual_v1'],
}

TTS_VOICE_NAME_CHOICES = {
    'GOOGLE': [
        "Zephyr", "Puck", "Charon",
        "Kore", "Fenrir", "Leda",
        "Orus", "Aoede", "Callirrhoe",
        "Autonoe", "Enceladus", "Iapetus",
        "Umbriel", "Algieba", "Despina",
        "Erinome", "Algenib", "Rasalgethi",
        "Laomedeia", "Achernar", "Alnilam",
        "Schedar", "Gacrux", "Pulcherrima",
        "Achird", "Zubenelgenubi", "Vindemiatrix",
        "Sadachbia", "Sadaltager", "Sulafat"
    ],
    'ELEVENLABS': [
        "JBFqnCBsd6RMkjVDRZzb",  # Emma
        "EXAVITQu4vr4xnSDxMaL",  # Adam
        "21m00Tcm4TlvDq8ikWAM",  # Rachel
        "ErXwobaYiN019PkySvjV",  # Domi
        "MF3mGyEYCl7XYWbV9V6O",  # Bella
        "TxGEqnHWrfWFTfGW9XjX",  # Josh
        "VR6AewLTigWG4xSOukaG",  # Sam
        "AZnzlk1XvdvUeBnXmlld",  # Elli
    ],
}




